Feature/about
DannyPennington/QA_Cinema-Team3 pull request #42
Opened 2020-03-31 15:44 UTC by AIbrahimQA

2020-03-31 16:06 UTC, DannyPennington requested changes
Looks good, just needs these changes to compile correctly

2020-03-31 16:06 UTC, DannyPennington commented on app/controllers/HomeController.scala
> +  def about: Action[AnyContent] = Action {
```suggestion
  def about: Action[AnyContent] = Action { implicit request:Request[AnyContent] =>
```

2020-03-31 16:06 UTC, DannyPennington commented on app/controllers/HomeController.scala
> +  def about: Action[AnyContent] = Action {
implicit request required for header to compile

2020-03-31 16:06 UTC, DannyPennington commented on app/views/about.scala.html
> +@()
```suggestion
@()(implicit request: Request[AnyContent])
```

2020-03-31 21:38 UTC, DannyPennington approved these changes

2020-04-01 11:10 UTC, JoNB7777 approved these changes

2020-04-01 11:13 UTC, merged