Feature/css about
DannyPennington/QA_Cinema-Team3 pull request #48
Opened 2020-04-01 14:28 UTC by AIbrahimQA

2020-04-01 15:08 UTC, DannyPennington requested changes
Nice work, just some little edits

2020-04-01 15:08 UTC, DannyPennington commented on app/views/about.scala.html
> +            <p class="about_para" We provide a variety of up-to-date films with different classifications to choose from which are shown on state of the art screens.<br>
```suggestion
            <p class="about_para"> We provide a variety of up-to-date films with different classifications to choose from which are shown on state of the art screens.<br>
```

2020-04-01 15:08 UTC, DannyPennington commented on app/views/about.scala.html
> +            <p class="about_para" We provide a variety of up-to-date films with different classifications to choose from which are shown on state of the art screens.<br>
Some of the text doesn't show on the page, I think this might be why

2020-04-01 15:08 UTC, DannyPennington commented on app/views/about.scala.html
> +            <a class = "btn-lg btn-light" href="http://localhost:9000/contactUs" style="padding: 20px;">Contact Page</a>
```suggestion
            <a class = "btn-lg btn-light" href="@routes.ContactUsController.contact" style="padding: 20px;">Contact Page</a>
```

2020-04-01 15:08 UTC, DannyPennington commented on app/views/about.scala.html
> +            <a class = "btn-lg btn-light" href="http://localhost:9000/contactUs" style="padding: 20px;">Contact Page</a>
Changed to reverse route over hard-coded link

2020-04-01 16:01 UTC, DannyPennington approved these changes

2020-04-02 08:52 UTC, SamWhite745 approved these changes

2020-04-02 08:53 UTC, merged